name: Build Flatpak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: flatpak/org.gnu.Guile.yaml
          arch: amd64
          bundle: guile.flatpak

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: guile-flatpak
          path: guile.flatpak
