name: MSYS

on:
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set git to Linux line endings
      run: git config --global core.autocrlf input

    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Install Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        install: >-
          autotools
          flex
          gcc
          gettext-devel
          git
          gmp-devel
          gperf
          libffi-devel
          libgc-devel
          libiconv-devel
          libintl
          libreadline-devel
          libunistring-devel
          lzip
          pkgconf 
          texinfo
          xz

    - name: Git clone Guile
      run: |
        git clone --branch staging https://github.com/spk121/guile.git
      shell: msys2 -o igncr '{0}'

    # This uses MSYS's bash
    - name: Configure
      run: |
        set -e
        export LANG=C.UTF-8
        export TERM=dumb
        export VERBOSE=true
        export TZ=America/Los_Angeles
        cd guile
        ./autogen.sh
        ./configure CFLAGS="-g -O2 -Wall" --disable-lto
      shell: msys2 -o igncr '{0}'

    # This uses MSYS's bash
    - name: Build
      run: |
        set -e
        cd guile
        make -j4 V=1 2>&1 | tee build.log
      shell: msys2 -o igncr '{0}'

    # This uses MSYS's bash
    - name: Check
      run: |
        set -e
        cd guile
        make check 2>&1 | tee check.log
      shell: msys2 -o igncr '{0}'

    - name: Archive Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Logs
        path: ./guile/*.log
        if-no-files-found: warn
