name: Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: basic, thread: --without-threads, jit: --enable-jit=no,  gmp: --enable-mini-gmp }
          - { sys: default, thread: --with-threads, jit: --enable-jit=yes, gmp: --disable-mini-gmp }

    runs-on: ubuntu-latest
    name: Build ${{matrix.sys}} ${{matrix.thread}} ${{matrix.jit}} ${{matrix.gmp}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq \
          texlive \
          texlive-plain-generic \
          texinfo \
          autoconf \
          libtool \
          gettext \
          autopoint \
          gperf \
          pkg-config \
          lzip \
          libgc-dev \
          libgmp-dev \
          libltdl-dev \
          libncurses5-dev \
          libreadline-dev \
          libunistring-dev \
          locales
        sudo locale-gen en_US.UTF-8
        sudo update-locale LANG=en_US.UTF-8

    - name: Git clone subprojects
      run: |
        git clone --branch staging --depth 1 https://github.com/spk121/guile.git
        
    - name: Configure
      run: |
        export LANG=C.UTF-8
        export TERM=dumb
        export VERBOSE=true
        export DEBIAN_FRONTEND=noninteractive
        export TZ=America/Los_Angeles
        cd guile
        ./autogen.sh
        ./configure CFLAGS="-g -O2" ${{ matrix.thread }} ${{ matrix.jit }} ${{ matrix.gmp }}

    - name: Build
      run: |
        cd guile
        make -j$(nproc) V=1

    - name: Check
      run: |
        cd guile
        make check -k V=1

    - name: Archive Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test Logs  ${{ matrix.thread }} ${{ matrix.jit }} ${{ matrix.gmp }}
        path: |
          guile/*.log
          guile/test-suite/tests/*.log
        if-no-files-found: warn
